(07/01/2019 12:45:31 PM) ERROR:Internal Server Error: /documentation/
Traceback (most recent call last):
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'endblock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/core/handlers/base.py", line 154, in _get_response
    response = response.render()
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/loaders/base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 194, in compile_nodelist
    return parser.parse()
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/loader_tags.py", line 266, in do_extends
    nodelist = parser.parse()
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/loader_tags.py", line 209, in do_block
    nodelist = parser.parse(('endblock',))
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/defaulttags.py", line 951, in do_if
    nodelist = parser.parse(('elif', 'else', 'endif'))
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 528, in invalid_block_tag
    get_text_list(["'%s'" % p for p in parse_until], 'or'),
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 37: 'endblock', expected 'elif', 'else' or 'endif'. Did you forget to register or load this tag?
(07/01/2019 12:46:51 PM) WARNING:Bad Request: /autoadds/
(07/01/2019 02:17:49 PM) ERROR:Internal Server Error: /admin/course/course/
Traceback (most recent call last):
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/db/models/options.py", line 564, in get_field
    return self.fields_map[field_name]
KeyError: 'get_subjects'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/contrib/admin/utils.py", line 278, in lookup_field
    f = _get_non_gfk_field(opts, name)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/contrib/admin/utils.py", line 309, in _get_non_gfk_field
    field = opts.get_field(name)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/db/models/options.py", line 566, in get_field
    raise FieldDoesNotExist("%s has no field named '%s'" % (self.object_name, field_name))
django.core.exceptions.FieldDoesNotExist: Course has no field named 'get_subjects'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/core/handlers/base.py", line 154, in _get_response
    response = response.render()
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/contrib/admin/templatetags/base.py", line 33, in render
    return super().render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/contrib/admin/templatetags/admin_list.py", line 341, in result_list
    'results': list(results(cl))}
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/contrib/admin/templatetags/admin_list.py", line 318, in results
    yield ResultList(None, items_for_result(cl, res, None))
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/contrib/admin/templatetags/admin_list.py", line 309, in __init__
    super().__init__(*items)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/contrib/admin/templatetags/admin_list.py", line 228, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/contrib/admin/utils.py", line 291, in lookup_field
    value = attr()
  File "/Users/mfhodges/Desktop/CRF2/crf2/course/models.py", line 241, in get_subjects
    return ",\n".join([sub.abbreviation for sub in cross_listed])
TypeError: 'ManyRelatedManager' object is not iterable
(07/01/2019 05:37:38 PM) WARNING:Bad Request: /requests/
(07/01/2019 05:38:12 PM) WARNING:Bad Request: /requests/
(07/01/2019 05:42:29 PM) ERROR:Internal Server Error: /requests/
Traceback (most recent call last):
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/rest_framework/viewsets.py", line 116, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/mfhodges/Desktop/CRF2/crf2/course/views.py", line 380, in create
    serializer = self.get_serializer(instance, data=d)
NameError: name 'instance' is not defined
(07/01/2019 05:43:16 PM) WARNING:Bad Request: /requests/
(07/01/2019 05:43:20 PM) WARNING:Bad Request: /requests/
(07/01/2019 05:43:54 PM) WARNING:Bad Request: /requests/AAMW5264012019C/
(07/01/2019 05:45:09 PM) WARNING:Bad Request: /requests/
(07/01/2019 05:47:42 PM) WARNING:Bad Request: /requests/
(07/01/2019 05:48:05 PM) ERROR:Internal Server Error: /requests/
Traceback (most recent call last):
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/rest_framework/viewsets.py", line 116, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/mfhodges/Desktop/CRF2/crf2/course/views.py", line 402, in create
    self.perform_create(serializer)
  File "/Users/mfhodges/Desktop/CRF2/crf2/course/views.py", line 422, in perform_create
    serializer.save(owner=self.request.user)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/rest_framework/serializers.py", line 214, in save
    self.instance = self.create(validated_data)
  File "/Users/mfhodges/Desktop/CRF2/crf2/course/serializers.py", line 309, in create
    add_enrolls_data = validated_data.pop('additional_enrollments')
KeyError: 'additional_enrollments'
(07/01/2019 05:53:11 PM) ERROR:Internal Server Error: /courses/AAMW6354012019C/
Traceback (most recent call last):
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/core/handlers/base.py", line 154, in _get_response
    response = response.render()
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/rest_framework/response.py", line 72, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/rest_framework/renderers.py", line 177, in render
    return template.render(context, request=request)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/loader_tags.py", line 188, in render
    return template.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 173, in render
    return self._render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/defaulttags.py", line 165, in render
    values = list(values)
TypeError: 'RelatedManager' object is not iterable
(07/01/2019 05:53:35 PM) ERROR:Internal Server Error: /courses/AAMW6354012019C/
Traceback (most recent call last):
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/core/handlers/base.py", line 154, in _get_response
    response = response.render()
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/rest_framework/response.py", line 72, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/rest_framework/renderers.py", line 177, in render
    return template.render(context, request=request)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/loader_tags.py", line 188, in render
    return template.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 173, in render
    return self._render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/defaulttags.py", line 165, in render
    values = list(values)
TypeError: 'RelatedManager' object is not iterable
(07/01/2019 05:55:06 PM) WARNING:Not Found: /api/course/AAMW6354012019C/
(07/01/2019 05:55:14 PM) DEBUG:Successfuly imported extension module "markdown.extensions.toc".
(07/01/2019 05:55:14 PM) DEBUG:Successfully loaded extension "markdown.extensions.toc.TocExtension".
(07/01/2019 05:55:18 PM) DEBUG:Successfuly imported extension module "markdown.extensions.toc".
(07/01/2019 05:55:18 PM) DEBUG:Successfully loaded extension "markdown.extensions.toc.TocExtension".
(07/01/2019 05:58:42 PM) DEBUG:Successfuly imported extension module "markdown.extensions.toc".
(07/01/2019 05:58:42 PM) DEBUG:Successfully loaded extension "markdown.extensions.toc.TocExtension".
(07/01/2019 05:58:53 PM) DEBUG:Successfuly imported extension module "markdown.extensions.toc".
(07/01/2019 05:58:53 PM) DEBUG:Successfully loaded extension "markdown.extensions.toc.TocExtension".
(07/01/2019 05:59:13 PM) DEBUG:Successfuly imported extension module "markdown.extensions.toc".
(07/01/2019 05:59:13 PM) DEBUG:Successfully loaded extension "markdown.extensions.toc.TocExtension".
(07/01/2019 05:59:15 PM) DEBUG:Successfuly imported extension module "markdown.extensions.toc".
(07/01/2019 05:59:15 PM) DEBUG:Successfully loaded extension "markdown.extensions.toc.TocExtension".
(07/02/2019 09:45:44 AM) ERROR:Internal Server Error: /
Traceback (most recent call last):
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/core/handlers/base.py", line 154, in _get_response
    response = response.render()
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/rest_framework/response.py", line 72, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/rest_framework/renderers.py", line 177, in render
    return template.render(context, request=request)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/defaulttags.py", line 442, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/urls/base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/urls/resolvers.py", line 622, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for '{{ course }}_{{ Notice }}' not found. '{{ course }}_{{ Notice }}' is not a valid view function or pattern name.
(07/02/2019 09:45:44 AM) WARNING:Not Found: /favicon.ico
(07/02/2019 09:46:47 AM) ERROR:Internal Server Error: /
Traceback (most recent call last):
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/core/handlers/base.py", line 154, in _get_response
    response = response.render()
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/rest_framework/response.py", line 72, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/rest_framework/renderers.py", line 177, in render
    return template.render(context, request=request)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/defaulttags.py", line 442, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/urls/base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/urls/resolvers.py", line 622, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'course_Notice' not found. 'course_Notice' is not a valid view function or pattern name.
(07/02/2019 09:46:59 AM) ERROR:Internal Server Error: /
Traceback (most recent call last):
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/core/handlers/base.py", line 154, in _get_response
    response = response.render()
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/rest_framework/response.py", line 72, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/rest_framework/renderers.py", line 177, in render
    return template.render(context, request=request)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/defaulttags.py", line 442, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/urls/base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/urls/resolvers.py", line 622, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'course_notice' not found. 'course_notice' is not a valid view function or pattern name.
(07/02/2019 09:48:31 AM) ERROR:Internal Server Error: /
Traceback (most recent call last):
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/core/handlers/base.py", line 154, in _get_response
    response = response.render()
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/rest_framework/response.py", line 72, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/rest_framework/renderers.py", line 177, in render
    return template.render(context, request=request)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/template/defaulttags.py", line 442, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/urls/base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/Users/mfhodges/Desktop/CRF2/envcrf/lib/python3.6/site-packages/django/urls/resolvers.py", line 622, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'course_notice_changelist_change' not found. 'course_notice_changelist_change' is not a valid view function or pattern name.
